name: VetSmart Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Asegúrate de usar la versión adecuada de Node.js

      - name: Install dependencies for frontend
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          SSH_HOST: ${{ secrets.VPS_SSH_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}
        run: |
          # Crear directorios en el VPS
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" 'mkdir -p /var/www/html/vetsmart'

          # Copiar el build del frontend al VPS
          sshpass -p "${SSH_PASSWORD}" rsync -avz --delete -e "sshpass -p '${SSH_PASSWORD}' ssh -o StrictHostKeyChecking=no" ./dist/ "${SSH_USERNAME}@${SSH_HOST}:/var/www/html/vetsmart"

          # Comando adicional para asegurarse de que los permisos sean correctos y Nginx se reinicie
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" << 'EOF'
            sudo chown -R www-data:www-data /var/www/html/vetsmart
            sudo systemctl restart nginx
          EOF
