name: VetSmart Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          SSH_HOST: ${{ secrets.VPS_SSH_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Utiliza la clave SSH privada
        run: |
          # Crear directorios en el VPS
          ssh -i <(echo "${SSH_PRIVATE_KEY}") -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" 'mkdir -p /var/www/html/vetsmart'

          # Copiar el build del frontend al VPS
          rsync -avz --delete -e "ssh -i <(echo '${SSH_PRIVATE_KEY}') -o StrictHostKeyChecking=no" ./dist/ "${SSH_USERNAME}@${SSH_HOST}:/var/www/html/vetsmart"
          
          # Comando adicional para asegurarse de que los permisos sean correctos y Nginx se reinicie
          ssh -i <(echo "${SSH_PRIVATE_KEY}") -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" << 'EOF'
            sudo chown -R www-data:www-data /var/www/html/vetsmart
            sudo systemctl restart nginx
          EOF
